version: '3'

services:
  mariadb:
    image: mariadb
    container_name: mariadb
    build:
      context: ./requirements/mariadb
      dockerfile: Dockerfile
    volumes:
      - mariadb:/var/lib/mysql
    expose:
      - "3306"
    networks:
      - inception
    restart: unless-stopped
    env_file: 
      - .env
    healthcheck:
      test: mysqladmin ping --host=localhost -p${SQL_ROOT_PASSWORD}
      interval: 5s
      timeout: 1s
      retries: 20
      #start_period: 5s
  redis:
    container_name: redis
    build: requirements/bonus/redis/.
    image:  redis
    volumes:
      - wordpress:/var/www/html
    expose:
      - "6379"
    restart:  unless-stopped
    networks:
      - inception

  wordpress:
    image: wordpress
    container_name: wordpress
    build:
      context: ./requirements/wordpress
      dockerfile: Dockerfile
    volumes:
      - wordpress:/var/www/html/wordpress
    expose:
      - "9000"
    networks:
      - inception
    restart: unless-stopped
    env_file: 
      - .env
    depends_on:
      mariadb :
        condition: service_healthy

  nginx:
    image: nginx
    container_name: nginx
    build:
      context: ./requirements/nginx
      dockerfile: Dockerfile
    volumes:
      - wordpress:/var/www/html/wordpress
    depends_on:
      - wordpress
      - hugo
      - adminer
    ports:
      - "443:443"
    networks:
      - inception
    restart: unless-stopped
    env_file: 
      - .env
    healthcheck:
      test: ["CMD", "pidof", "nginx"]
      interval: 5s
      timeout: 1s
      retries: 10
      #start_period: 5s

  ftp-server:
      image: ftp-server
      container_name: ftp_server
      build:
        context: ./requirements/bonus/ftp
        dockerfile: Dockerfile
      volumes:
        - wordpress:/var/www/html/wordpress
      depends_on:
        - wordpress
      ports:
        - "21:21"
      networks:
        - inception
      restart: unless-stopped
      env_file: 
        - .env
  adminer:
    image: adminer
    container_name: adminer
    build:
      context: ./requirements/bonus/adminer
      dockerfile: Dockerfile
    volumes: 
        - adminer:/var/www/html
    depends_on:
        - mariadb
    ports:
        - "9000"
    networks:
        - inception
    restart: unless-stopped
    env_file: 
        - .env
  hugo:
    container_name: hugo
    build: ./requirements/bonus/hugo
    restart: always
    networks:
      - inception

volumes:
  mariadb:
    driver: local
    driver_opts:
      type: 'none'
      o: 'bind'
      device: '/home/hinda/data/mariadb'
  wordpress:
    driver: local
    driver_opts:
      type: 'none'
      o: 'bind'
      device: '/home/hinda/data/wordpress'
  adminer:
    driver: local
    driver_opts:
      type: 'none'
      o: 'bind'
      device: '/home/hinda/data/adminer'

networks:
  inception:
    name: inception

# version: '3'

# services:
#   mariadb:
#     image: mariadb
#     container_name: mariadb
#     build:
#       context: ./requirements/mariadb
#       dockerfile: Dockerfile
#     volumes:
#       - mariadb:/var/lib/mysql
#     expose:
#       - "3306"
#     networks:
#       - inception
#     restart: unless-stopped
#     env_file: .env
#     healthcheck:
#       test: mysqladmin ping --host=localhost -p${SQL_ROOT_PASSWORD}
#       interval: 5s
#       timeout: 1s
#       retries: 20
#       start_period: 5s

#   wordpress:
#     image: wordpress
#     container_name: wordpress
#     build:
#       context: ./requirements/wordpress
#       dockerfile: Dockerfile
#     volumes:
#       - wordpress:/var/www/html/wordpress
#     expose:
#       - "9000"
#     networks:
#       - inception
#     restart: unless-stopped
#     env_file: .env
#     # depends_on:
#     #   mariadb:
#     #     condition: service_healthy   
  
#   redis:
#     container_name: redis
#     build: requirements/bonus/redis
#     image:  redis
#     volumes:
#       - wordpress:/var/www/html/wordpress
#     expose:
#       - "6379"
#     restart:  unless-stopped
#     networks:
#       - inception

#   nginx:
#     image: nginx
#     container_name: nginx
#     build:
#       context: ./requirements/nginx
#       dockerfile: Dockerfile
#     volumes:
#       - wordpress:/var/www/html/wordpress
#     depends_on:
#       - wordpress
#       - adminer
#       - redis
#       # - hugo
#     ports:
#       - "443:443"
#     networks:
#       - inception
#     restart: unless-stopped
#     env_file: .env
  
#   adminer:
#     image: adminer
#     container_name: adminer
#     build:
#       context: ./requirements/bonus/adminer
#       dockerfile: Dockerfile
#     volumes:
#       - adminer:/var/www/html
#     depends_on:
#       - mariadb
#     ports:
#       - "9000"
#     networks:
#       - inception
#     restart: unless-stopped

#   ftp-server:
#     image: ftp-server
#     container_name: ftp-server
#     build:
#       context: ./requirements/bonus/ftp
#       dockerfile: Dockerfile
#     volumes:
#       - wordpress:/var/www/html/wordpress
#     depends_on:
#       - wordpress
#     ports:
#       - "21:21"
#     networks:
#       - inception
#     restart: unless-stopped
#     env_file: .env

#   # hugo:
#   #   container_name: hugo
#   #   build: ./requirements/bonus/hugo
#   #   restart: always
#   #   networks:
#   #     - inception

# volumes:
#   mariadb:
#     driver: local
#     driver_opts:
#       type: 'none'
#       o: 'bind'
#       device: '/home/hinda/data/mariadb'
#   wordpress:
#     driver: local
#     driver_opts:
#       type: 'none'
#       o: 'bind'
#       device: '/home/hinda/data/wordpress'
#   adminer:
#     driver: local
#     driver_opts:
#       type: 'none'
#       o: 'bind'
#       device: '/home/hinda/data/adminer'

# networks:
#   inception:
#     name: inception